### ISSUE TITLE
Node Visualization 방향에 대해

### ISSUE THREAD

**Issue by CODe5753** [SOSCON-TheONE/Node-comparison-analysis#4]
## Json 쓰기가 필요한 이유
- 시각화 단계에서 로컬 json 정보를 읽어와 시각화하는 과정이 존재함
   ```html
   <!-- NodeGraphPanel.ts -->
   <script>
		d3.json("${nodeJsonDataUri}").then(function (json) {
			TreeMap(json);
		});
   </script>
   ```
- Sample typescript code
  ```typescript
  let jsondata = JSON.stringify(resultArr);
  writeFile('nodes-sample.json',jsondata,'utf8',function(err){
      console.log(err);
  });
  ```
## Visualization 과정
- 모든 노드의 정보를 읽고 index마다 노드를 등록함
- 각 노드의 parent node를 연결해줌
- 각 노드의 parent node 정보를 보고 각 index에 맞게 연결함
## Todo
- [x] 최상단 부모 노드를 등록해야 함 (tflite의 경우 `input` 노드가 등록이 안되는 문제를 발견함)
- [x] json 파일 쓰기까지 완료 되어야 함
- [x] 이 모든 과정이 Visualization 내에서 해결 되어야 함
- [x] 두 개의 json 파일과 circle을 매칭
- [x] duration 계산하기
